cc_library(
    name = "mutest",
    visibility = ["//visibility:public"],
    srcs = [
        "utest_main.cpp",
        "mutest/event_sink.cpp",
        "mutest/copy_error_tester.h",
        "mutest/detail/binary_op.h",
        "mutest/detail/char_stream.h",
        "mutest/detail/check.h",
        "mutest/detail/expr.h",
        "mutest/detail/list.h",
        "mutest/detail/registry.cpp",
        "mutest/detail/registry.h",
        "mutest/detail/repr.cpp",
        "mutest/detail/repr.h",
        ],
    hdrs = [
        "exec.h",
        "mutest/event_sink.h",
        "mutest/test.h",
        "mutest/utest.h",
        ],
    includes = ["."],
    )
